### ISSUE TITLE
php 5.3 is not supported anymore by travis

### ISSUE THREAD

**Issue by rimvislt** [mkoppanen/imagick#238]
PHP5.3 version tests fails with:
````
PHP 5.3 is supported only on Precise.
See https://docs.travis-ci.com/user/reference/trusty#PHP-images on how to test PHP 5.3 on Precise.
Terminating.
````

https://blog.travis-ci.com/2017-08-31-trusty-as-default-status
According blog:
````
end support for dist: precise | Sunday, April 1 2018
````

Should we remove tests for php5.3 ?

**Comment by Danack** [comment]
php 5.3 isn't supported by default but it is still available as a different image.

Setting something like

```
matrix:
  include:
    - php: 5.2
      dist: precise
    - php: 5.3
      dist: precise
```

should make it work.
